package com.github.webservicetesting

import org.junit.experimental.categories.Category
import spock.lang.Ignore
import spock.lang.Narrative

/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'amit' at '3/22/15 9:27 PM' with Gradle 2.2
 *
 * @author amit, @date 3/22/15 9:27 PM
 */

@Ignore
@Category( TodoServiceTests )
@Narrative("""
As a user I can create, update and delete a TodoItem
""")
class TodoItemUpdateOperationsSpec extends BaseSpecification{
    def "Create , Update and then Delete an Item"() {
        setup:
        TodoItem item = new TodoItem()
        when:
        def result = item
        then:
        result == true
    }
}
