/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'amit' at '3/22/15 9:27 PM' with Gradle 2.2
 *
 * @author amit, @date 3/22/15 9:27 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
