/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'amit' at '3/22/15 9:27 PM' with Gradle 2.2
 *
 * @author amit, @date 3/22/15 9:27 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
